// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWhg7vxUiTL4CaC4I9QhGkmEEtA2O6L4E',
    appId: '1:856202568320:web:c916b34937cda7e1f13c65',
    messagingSenderId: '856202568320',
    projectId: 'sippo-31b8b',
    authDomain: 'sippo-31b8b.firebaseapp.com',
    storageBucket: 'sippo-31b8b.appspot.com',
    measurementId: 'G-QS2MM3V273',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUXMfqrZyVGTfzX2XjkwRrBvUZnTapEdY',
    appId: '1:856202568320:android:b055fceaa935e081f13c65',
    messagingSenderId: '856202568320',
    projectId: 'sippo-31b8b',
    storageBucket: 'sippo-31b8b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsg-M3eKZyoVuXJ7Zv01HXjPq2x9BKEVo',
    appId: '1:856202568320:ios:f663fcee55dd289ff13c65',
    messagingSenderId: '856202568320',
    projectId: 'sippo-31b8b',
    storageBucket: 'sippo-31b8b.appspot.com',
    iosClientId:
        '856202568320-2hkmdbcfeq485ijqjhqollgj659n42gf.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobspot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsg-M3eKZyoVuXJ7Zv01HXjPq2x9BKEVo',
    appId: '1:856202568320:ios:f663fcee55dd289ff13c65',
    messagingSenderId: '856202568320',
    projectId: 'sippo-31b8b',
    storageBucket: 'sippo-31b8b.appspot.com',
    iosClientId:
        '856202568320-2hkmdbcfeq485ijqjhqollgj659n42gf.apps.googleusercontent.com',
    iosBundleId: 'com.example.jobspot',
  );
}
